### send a message to parent test api query

POST /trip-messages/send/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "student_id": "e69d8794-342c-4aa4-b56b-ced1487e1448",
  "trip_id": "aeb5022a-fd73-4e77-b1fd-6763785fe9e6"
}


###
POST https://transport-module.onrender.com/trip-messages/send-bulk/ HTTP/1.1
Host: transport-module.onrender.com
Content-Type: application/json

{
  "trip_id": "aeb5022a-fd73-4e77-b1fd-6763785fe9e6",
  "phone_numbers": [
    "0742675176"
  ]
}
###Send using mobile sasa api
POST /trip-messages/bulk-start-arrive-messages/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "trip_id": "9e533fac-c724-456a-8736-4aa07cbd6e3f",
  "student_ids": [
    "61e75a3f-e815-4c2a-b7b7-a59628e30df3",
    "3a07ec03-8d76-4abe-a64c-eac18002587c"
  ]
}