### Register User
PUT http://localhost:8000/users/f9bbf388-424c-4b11-ada1-4b8f099b2357/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "email": "test@exasrmpls.com",
  "username": "test-accosuntd",
  "password": "test-account1234",
  "phone_number": "+1234567890",
  "user_type": "TRIP_TEACHER",
  "school": "9984c0da-82bc-4581-88f1-971e8beefc1a"
}



### Register a previlaged user

POST http://localhost:8000/users/create-privileged/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "email": "mockuser@example.com",
  "username": "mock-user",
  "password": "mock-user1234",
  "phone_number": "+1234567890",
  "user_type": "TRIP_TEACHER",
  "school": "9984c0da-82bc-4581-88f1-971e8beefc1a"
}








### Get JWT Token
POST http://localhost:8000/auth/token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "username": "newuser",
  "password": "temporarypassword123"
}








### Use the signed url
POST http://localhost:8000/users/invite-user/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "user_type": "SCHOOL_ADMIN"
}


### Create a new user through the invitation link
POST http://localhost:8000/users/accept-invite/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "token": "58b6f548-4fa9-4b24-be60-77fb41035e25",
  "email": "kasipwusal@gmail.com",
  "username": "sapursuw",
  "password": "securePassword",
  "phone_number": "09123256789"
}

