# Generated by Django 5.2 on 2025-04-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TRIP_TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.user'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle'),
        ),
    ]
