# Generated by Django 5.2 on 2025-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_action',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('special', 'Special')], max_length=10),
        ),
    ]
