# Generated by Django 5.2 on 2025-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('trips', '0003_trip_trip_action_alter_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='boarded_students',
            field=models.ManyToManyField(blank=True, related_name='boarded_trips', to='students.student'),
        ),
        migrations.AddField(
            model_name='trip',
            name='expected_students',
            field=models.ManyToManyField(blank=True, related_name='expected_trips', to='students.student'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('morning_pickup', 'Morning Pickup'), ('evening_dropoff', 'Evening Dropoff')], max_length=20),
        ),
    ]
