# Generated by Django 5.2 on 2025-04-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SCHOOL_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_schools', to='users.user'),
        ),
    ]
