# Generated by Django 5.2 on 2025-06-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitation_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
    ]
