### Create a Trip

POST http://localhost:8000/trips/
Content-Type: application/json

{
  "name": "Morning Pickup",
  "trip_type": "normal",
  "trip_action": "pickup",
  "trip_status": "ongoing",
  "school": "da22b406-50f6-4e8d-afd7-ed52e5d0f6ad",
  "vehicle": "982dbb9b-005a-4dea-995d-91fc4e16f4d5",
  "driver": "abcadba0-7af4-4d7f-a69e-3e3ac7ad0040",
  "trip_teacher": "287a1457-8a4d-4817-86c2-22f12f2670e0",
  "route": "7ee67271-a068-4ba9-ac75-5a83e88b732c",
  "start_location": "Main Gate",
  "end_location": "School",
  "departure_time": "2025-04-30T07:30:00Z",
  "arrival_time": null
}



### List all the trips
GET http://localhost:8000/trips/


### Update a trip
PUT http://localhost:8000/trips/9e533fac-c724-456a-8736-4aa07cbd6e3f/
Content-Type: application/json

{
  "name": "Afternoon Dropoff",
  "trip_type": "special",
  "trip_action": "dropoff",
  "trip_status": "ongoing",
  "school": "da22b406-50f6-4e8d-afd7-ed52e5d0f6ad",
  "vehicle": "982dbb9b-005a-4dea-995d-91fc4e16f4d5",
  "driver": "abcadba0-7af4-4d7f-a69e-3e3ac7ad0040",
  "trip_teacher": "287a1457-8a4d-4817-86c2-22f12f2670e0",
  "route": "7ee67271-a068-4ba9-ac75-5a83e88b732c",
  "start_location": "School",
  "end_location": "Bus Stop",
  "departure_time": "2025-04-30T13:00:00Z",
  "arrival_time": null
}


### Delete a trip
DELETE http://localhost:8000/trips/9e533fac-c724-456a-8736-4aa07cbd6e3f/
