
### Create a driver
POST http://localhost:8000/drivers/ HTTP/1.1
Host: localhost:8000  
Content-Type: application/json  

{
  "full_name": "John Mboya",
  "phone_number": "+254712345678",
  "school": "da22b406-50f6-4e8d-afd7-ed52e5d0f6ad"
}


### List all drivers
GET http://localhost:8000/drivers/ HTTP/1.1
Host: localhost:8000  


### Update a driver instance
PUT http://localhost:8000/drivers/294c493f-7ede-4387-b134-0589d0386a34/ HTTP/1.1
Host: localhost:8000  
Content-Type: application/json  

{
  "full_name": "John Mboya Jr.",
  "phone_number": "+254712345679",
  "school": "da22b406-50f6-4e8d-afd7-ed52e5d0f6ad"
}



### Delete a driver instane
DELETE http://localhost:8000/drivers/294c493f-7ede-4387-b134-0589d0386a34/ HTTP/1.1
Host: localhost:8000  