# Generated by Django 5.2 on 2025-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
