# Generated by Django 5.2 on 2025-06-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=50, unique=True)),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=15)),
                ('message_content', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('network', models.CharField(choices=[('Safaricom', 'Safaricom'), ('Airtel', 'Airtel'), ('Telkom', 'Telkom')], max_length=20)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Sent', 'Sent')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
