# Generated by Django 5.2 on 2025-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('Promotional', 'Promotional'), ('Transactional', 'Transactional')], max_length=20, null=True),
        ),
    ]
